"""
Django settings for Django_Learn_YHZ project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '961z-+!jaq)o(i7k3!u!er)gj6d4w3eofwtp^vys&z%sgmvoq='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 只允许列表中的ip地址访问
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',           # 管理后台
    'django.contrib.auth',            # 身份验证系统
    'django.contrib.contenttypes',    # 内容类型框架
    'django.contrib.sessions',        # 会话框架
    'django.contrib.messages',        # 消息框架
    'django.contrib.staticfiles',     # 管理静态文件的框架
    'app1',  # 第一步，创建app后进行注册
]

# middleware 中间件
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # csrf警告
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 项目名称
ROOT_URLCONF = 'Django_Learn_YHZ.urls'

# 注册静态网页地址
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'Django_Learn_YHZ.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# 或者采用mysql，代码如下
# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        'NAME': '。。。',           # 你的数据库名称
#        'USER': 'root',            # 你的数据库用户名
#        'PASSWORD': '123456',      # 你的数据库密码
#        'HOST': '',                # 你的数据库主机，留空默认为localhost
#        'PORT': '3306',            # 你的数据库端口
#    }
# }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'

LANGUAGE_CODE = 'zh-hans'       # 中文
TIME_ZONE = 'Asia/Shanghai'     # 中国时区

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# setting配置三步走
# 1、注册APP，（INSTALLED_APPS）
# 2、配置模版路径，（新版django已默认配置）
# 3、配置静态文件，（新版django已默认配置）
#   STATICFILES_DIRS = (
#       os.path.join(BASE_DIR, 'static'),
#    )
