# Generated by Django 2.2.5 on 2020-03-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
